Traceback (most recent call last):
  File "/home/weiss/Desktop/lowcrossing_dehn/subgroup_invariant/snappy_distinguish_remaining_pairs.py", line 208, in <module>
    compute_covers_in_parallel(knots, computed_invariants_csv, deg=deg, num_workers=num_workers, debug_level=debug_level, timeout=timeout)
  File "/home/weiss/Desktop/lowcrossing_dehn/subgroup_invariant/snappy_distinguish_remaining_pairs.py", line 118, in compute_covers_in_parallel
    with ProcessPool(max_workers=num_workers) as pool:
  File "/home/weiss/.local/lib/python3.10/site-packages/pebble/pool/base_pool.py", line 44, in __exit__
    self.join()
  File "/home/weiss/.local/lib/python3.10/site-packages/pebble/pool/base_pool.py", line 72, in join
    self._wait_queue_depletion(timeout)
  File "/home/weiss/.local/lib/python3.10/site-packages/pebble/pool/base_pool.py", line 86, in _wait_queue_depletion
    time.sleep(SLEEP_UNIT)
  File "src/cysignals/signals.pyx", line 310, in cysignals.signals.python_check_interrupt
KeyboardInterrupt
Exception ignored in atexit callback: <function interpreter_shutdown at 0x7fd4b06324d0>
Traceback (most recent call last):
  File "/home/weiss/.local/lib/python3.10/site-packages/pebble/pool/process.py", line 491, in interpreter_shutdown
    stop_process(worker)
  File "/home/weiss/.local/lib/python3.10/site-packages/pebble/common.py", line 149, in stop_process
    process.join(3)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "src/cysignals/signals.pyx", line 310, in cysignals.signals.python_check_interrupt
KeyboardInterrupt: 
